USE [master]
GO

/****** Object:  Database [SchoolMaster]    Script Date: 12/15/2020 6:11:18 PM ******/
CREATE DATABASE [SchoolMaster]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SchoolMaster', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SchoolMaster.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SchoolMaster_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SchoolMaster_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SchoolMaster].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SchoolMaster] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SchoolMaster] SET ANSI_NULLS OFF
GO

ALTER DATABASE [SchoolMaster] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SchoolMaster] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SchoolMaster] SET ARITHABORT OFF 
GO

ALTER DATABASE [SchoolMaster] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SchoolMaster] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SchoolMaster] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SchoolMaster] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SchoolMaster] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SchoolMaster] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SchoolMaster] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SchoolMaster] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SchoolMaster] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SchoolMaster] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SchoolMaster] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SchoolMaster] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SchoolMaster] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SchoolMaster] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SchoolMaster] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SchoolMaster] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SchoolMaster] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SchoolMaster] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SchoolMaster] SET  MULTI_USER 
GO

ALTER DATABASE [SchoolMaster] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SchoolMaster] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SchoolMaster] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SchoolMaster] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SchoolMaster] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SchoolMaster] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SchoolMaster] SET  READ_WRITE 
GO


